openapi: "3.0.0"
info:
  version: 1.0.0
  title: Open API demo
  license:
    name: MIT
servers:
  - url: http://localhost:8080/v1
paths:
  /companies:
    get:
      summary: List all companies
      operationId: listCompanies
      tags:
        - companies
      responses:
        '200':
          description: A array of companies
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompaniesResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a company
      operationId: createCompany
      tags:
        - companies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyRequest'
        required: true
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /employees:
    get:
      summary: List all employees
      operationId: listEmployees
      tags:
        - employees
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            maximum: 100
            format: int32
      responses:
        '200':
          description: A paged array of employees
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmployeesResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create an employee
      operationId: createEmployee
      tags:
        - employees
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeRequest'
        required: true
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /employees/{employeeId}:
    get:
      summary: Info for a specific employee
      operationId: showEmployeeById
      tags:
        - employees
      parameters:
        - name: employeeId
          in: path
          required: true
          description: The id of an employee to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmployeeResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    CompanyRequest:
      type: object
      properties:
        company:
          $ref: "#/components/schemas/Company"
    EmployeeRequest:
      type: object
      properties:
        company:
          $ref: "#/components/schemas/Employee"
    CompanyResponse:
      type: object
      properties:
        company:
          $ref: "#/components/schemas/Company"
    EmployeeResponse:
      type: object
      properties:
        company:
          $ref: "#/components/schemas/Employee"
    CompaniesResponse:
      type: object
      properties:
        company:
          $ref: "#/components/schemas/Companies"
    EmployeesResponse:
      type: object
      properties:
        company:
          $ref: "#/components/schemas/Employees"
    Company:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        employees:
          $ref: "#/components/schemas/Employees"
    Employee:
      type: object
      required:
        - firstname
        - lastname
        - birthdate
      properties:
        id:
          type: integer
          format: int64
        firstname:
          type: string
        lastname:
          type: string
        birthdate:
          type: string
    Companies:
      type: array
      items:
        $ref: "#/components/schemas/Company"
    Employees:
      type: array
      maxItems: 100
      items:
        $ref: "#/components/schemas/Employee"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        status:
          type: integer
          format: int32
        title:
          type: string
        type:
          type: string
        detail:
          type: string
        instance:
          type: string
